### ISSUE TITLE
このレイアウトは可能？

### ISSUE THREAD

**Issue by yukidallas** [yukidallas/snakeholder#1]
![2016-10-23 pm 3 25 44](https://cloud.githubusercontent.com/assets/16233476/19624529/1182d2a6-9935-11e6-97ee-883f66650780.png)

text-align: center で揃えておき、"ゲームで人生を豊かにする" のフォントサイズと下の説明文の幅を揃えるなんて可能なのか？

フォントサイズはブラウザによって変わるからできたとしても全てが揃うとは限らない。

**Comment by ShimabukuroYuki** [comment]
まじか...
どれくらい差分ができるか確認したいです...

**Comment by yukidallas** [comment]
もし揃えられたとしてもこうなるのがオチ
<img width="691" alt="2016-10-29 pm 4 54 05" src="https://cloud.githubusercontent.com/assets/16233476/19828101/61a746dc-9df8-11e6-9443-21a9331de07c.png">

**Comment by yukidallas** [comment]
しょうがない
