### ISSUE TITLE
PC版とSP版の定義について

### ISSUE THREAD

**Issue by yukidallas** [yukidallas/snakeholder#10]
タブレットをモバイルに含めるか含めないかでコーディングが変わってくる。

<img width="704" alt="2016-10-23 pm 5 48 24" src="https://cloud.githubusercontent.com/assets/16233476/19625058/01643b6c-9949-11e6-860a-8bed6085bba0.png">

どちらが良いですかね？コメントください。

**Comment by ShimabukuroYuki** [comment]
タブレットはモバイルに含めなくても良さげかなぁ

**Comment by yukidallas** [comment]
おっけー！
