### ISSUE TITLE
画像の比率を揃えたい

### ISSUE THREAD

**Issue by yukidallas** [yukidallas/snakeholder#11]
<img width="719" alt="2016-10-23 pm 6 08 11" src="https://cloud.githubusercontent.com/assets/16233476/19625154/bad275d0-994b-11e6-9e06-9b51649fe5c6.png">

コード側で揃えることも可能だが、比率が崩れる。
Photoshopとかでリサイズ可能なのだろうか
# 現在

``` css
width: 200px;
height: 150px;
```

みたいにやっている
# 理想

``` css
width: 200px;
```

**Comment by ShimabukuroYuki** [comment]
画像の高さ、揃えてまた渡します！
