### ISSUE TITLE
ContactページのフォームURLがない

### ISSUE THREAD

**Issue by yukidallas** [yukidallas/snakeholder#12]
<img width="638" alt="2016-10-23 pm 6 15 18" src="https://cloud.githubusercontent.com/assets/16233476/19625191/bc44bc60-994c-11e6-9c89-baa0c7ae5925.png">

どこに飛ばすのか、どのような動作に持っていけば良いのか。

**Comment by ShimabukuroYuki** [comment]
左がgoogleフォームに飛ばすらしく、右が本多さんに直接メールがいくようにするみたい！
その辺は2人に聞いた方が良さそう！

**Comment by yukidallas** [comment]
修正済み
