### ISSUE TITLE
トランプのデザイン

### ISSUE THREAD

**Issue by yukidallas** [yukidallas/snakeholder#13]
![2016-10-23 pm 6 47 03](https://cloud.githubusercontent.com/assets/16233476/19625352/1d184f26-9951-11e6-973d-0929fafaea8f.png)

コーディング中に、トランプの背面ってこんな感じだったけ？と思った。
ユナイテッド航空のトランプを思い出したので作ってみた。(どうかなーという提案)

<img width="966" alt="2016-10-23 pm 6 43 26" src="https://cloud.githubusercontent.com/assets/16233476/19625335/a7d93428-9950-11e6-904b-3bbfad992d4b.png">

トランプで画像検索したら人のほうばかり出てきた。

**Comment by ShimabukuroYuki** [comment]
それ、イイかもしんない！外の枠を白じゃなく赤にしてみて！

**Comment by yukidallas** [comment]
わーい

**Comment by yukidallas** [comment]
<img width="974" alt="2016-11-01 pm 7 11 36" src="https://cloud.githubusercontent.com/assets/16233476/19886544/0df4c340-a067-11e6-9567-29f8f69498fb.png">
