### ISSUE TITLE
ゲーム一覧の数

### ISSUE THREAD

**Issue by yukidallas** [yukidallas/snakeholder#14]
特にゲーム名も画像もないのでどうなってるかよくわかりませんが、合計6つで良いのでしょうか？
![2016-10-23 pm 7 59 36](https://cloud.githubusercontent.com/assets/16233476/19625719/4a6518c4-995b-11e6-949f-a9ec8b6b794f.png)

**Comment by ShimabukuroYuki** [comment]
とりあえず6つで！
