### ISSUE TITLE
Planのカラムが揃わない

### ISSUE THREAD

**Issue by yukidallas** [yukidallas/snakeholder#15]
<img width="1236" alt="2016-10-23 pm 8 05 10" src="https://cloud.githubusercontent.com/assets/16233476/19625762/382ef6c4-995c-11e6-9bac-59b2ceb7f35f.png">

ウィンドウサイズによって行の折り返しが決まるため、各カラムの高さを決める必要がある。

**Comment by ShimabukuroYuki** [comment]
1番大きい「オーダーメイド」の大きさに揃えてみてください！

**Comment by yukidallas** [comment]
揃った！
