### ISSUE TITLE
iPhone safariでのhoverが動かない問題

### ISSUE THREAD

**Issue by yukidallas** [yukidallas/snakeholder#16]
# 概要

<img width="554" alt="2016-10-23 pm 11 48 47" src="https://cloud.githubusercontent.com/assets/16233476/19627143/4748334a-997b-11e6-8ce1-9613114e4c7a.png">
メニューのカードにカーソルを乗せるとカードが少し上に動く仕掛け。
Safariだとhoverイベントが特殊なため、現状動作しない。
# 対応策

そもそもスマホでhoverアニメーションはあまりない気がする。
とりあえず無視。

**Comment by ShimabukuroYuki** [comment]
何かいい動きないものか...

**Comment by yukidallas** [comment]
〜スマホ〜
UX >>>>>>>> アニメーション
