### ISSUE TITLE
細かいあーだこーだ

### ISSUE THREAD

**Issue by ShimabukuroYuki** [yukidallas/snakeholder#18]
- [x] メニュートランプの挙動(カクカクなのを滑らかに)
- [x] About画像の比率(狼少年げえむ以外の2つが潰れてる感ある)
- [x] アイコンドロップシャドウ(消しといて！)
- [x] 円グラフ
- [x] ゲーム画像のドロップシャドウ
- [x] activity仕切り線

**Comment by yukidallas** [comment]
height指定したままだったからやっぱり画像が揃ってなかった。もともと素材がアレなのでこっちで揃えます

![2016-11-05 pm 5 32 21](https://cloud.githubusercontent.com/assets/16233476/20028768/d9f1a9c2-a37d-11e6-8954-fe88c8c0b29d.png)

**Comment by ShimabukuroYuki** [comment]
了解！

**Comment by yukidallas** [comment]
ちゃんと直ってたら下にある[Close and comment] ボタンを押してください
