### ISSUE TITLE
PCとSPの背景色

### ISSUE THREAD

**Issue by yukidallas** [yukidallas/snakeholder#21]
セクション毎に違うがこれは正しいのか…？

![2016-11-05 pm 9 25 26](https://cloud.githubusercontent.com/assets/16233476/20029963/6b14bbb8-a39e-11e6-9479-fdc8b2080a3c.png)
![2016-11-05 pm 9 25 20](https://cloud.githubusercontent.com/assets/16233476/20029965/6bcfb058-a39e-11e6-82ed-52f90d450a60.png)

**Comment by ShimabukuroYuki** [comment]
おっけーです！
項目ごとに背景色変えてます！

**Comment by yukidallas** [comment]
ちゃうw PCのaboutは白、SPのaboutは灰色で異なっている と言いたい
