### ISSUE TITLE
Games: 白い線が気になる

### ISSUE THREAD

**Issue by yukidallas** [yukidallas/snakeholder#22]
box-shadow付けろとのことだったので付けたら気になった。

![2016-11-05 pm 9 34 47](https://cloud.githubusercontent.com/assets/16233476/20030026/b60d7c4e-a39f-11e6-9774-13d945585c4c.png)

**Comment by ShimabukuroYuki** [comment]
あ、そんじゃあとでカットしたの送る！
ちょっと時間経っちゃうけど！

**Comment by yukidallas** [comment]
白いの消えてなかったぞい！

**Comment by yukidallas** [comment]
👍🏻
