### ISSUE TITLE
Twitterウィジェットの埋め込み

### ISSUE THREAD

**Issue by yukidallas** [yukidallas/snakeholder#3]
僕が作っても良いですが、アカウント消したらウィジェットも消える可能性があるのでsnakeholderのアカウントか何かで生成してください。

https://twitter.com/settings/widgets/

Twitterウィジェットもテンプレがわかっているので、ある程度デザインがあったほうがいいと思いました。(Border消したりできる)

**Comment by ShimabukuroYuki** [comment]
どんくらいまでイジれる感じだ？

**Comment by yukidallas** [comment]
リファレンス見たら前見たときと変わってデザインが見れなくなってた
パラメーターってところ
https://dev.twitter.com/ja/web/embedded-timelines/parameters

**Comment by ShimabukuroYuki** [comment]
読んだが全くイメージつかねぇw
作りながら見ていくしかねぇかな...

**Comment by yukidallas** [comment]
明日提出でいきなり埋めろ言われても困るのでこっちで作ります。僕がアカウント消してウィジェット消えても知りませんwwwww (ほんとに消えるかは知らない)

**Comment by ShimabukuroYuki** [comment]
ほーい！

**Comment by yukidallas** [comment]
仕様が変わってアカウント関連なしでも生成できるようになってたw
