### ISSUE TITLE
Lightboxの導入

### ISSUE THREAD

**Issue by yukidallas** [yukidallas/snakeholder#4]
クリックしたらオーバーレイ表示をさせるのは把握してるが、何を表示する？
デザインがない。文章もない。

**Comment by ShimabukuroYuki** [comment]
後ほどデザインお送りします！
つーかいじくれるんだねwテンプレのまんま使うもんだと思ってた...

文章は2人に聞いた方がイイです！

**Comment by yukidallas** [comment]
<img width="842" alt="2016-10-29 17 06 58" src="https://cloud.githubusercontent.com/assets/16233476/19828604/a579eed4-9e05-11e6-8d1e-18bc4399ac7e.png">
