### ISSUE TITLE
デザイン全ての要素の大きさで小数が含まれている

### ISSUE THREAD

**Issue by yukidallas** [yukidallas/snakeholder#8]
![2016-10-23 pm 4 45 37](https://cloud.githubusercontent.com/assets/16233476/19624768/52911d1a-9940-11e6-8242-811500b5b50e.png)

コーディング側として、この数値でコーディングするのは避けたい。
一般的なサイトで大まかな要素で小数を使っている所は殆ど無い。

#現在の対応策
1の位で四捨五入 & 勘で指定

**Comment by ShimabukuroYuki** [comment]
すいません...感覚でやっている部分なので小数点入っちゃいました...
対応策の通りにやってもらっておkです！
